services:
  react:
    build: ./react
    container_name: react_c
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  # postgres
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "6000:6000"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  express-pg-server:
    build: ./express-pg-server
    container_name: express-pg-server_c
    ports:
      - "5000:5000"
    volumes:
      - ./express-pg-server:/app
      - /app/node_modules

volumes:
  postgres_data:
