###
GET http://localhost:5000
###

###
POST http://localhost:5000
Content-Type: application/json

{
    "name": "Calvin Phuah",
    "location":"Hello World Street"
}
###

###
GET http://localhost:5000/setup
###